spring:
  application:
    name: pgrest-boot-crud
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP

pgrest:
  base-url: http://127.0.0.1:3000
  service-name: postgrest-service
  db-role: api_user
  secret: reallyreallyreallyreallyverysafe
  jwt-ttl-seconds: 3600
  auth-enabled: true
  connect-timeout-millis: 5000
  read-timeout-millis: 10000
pgrest:
  gateway:
    enabled: true
pgrest:
  feign:
    enabled: true
    clients:
      A:
        serviceName: a-service
        mode: gateway
      B:
        serviceName: b-service
        mode: direct
        pathPrefix: /pgrest